#!/bin/bash

BOARD="0"
CHIP="0"
SPEED="0"
OPTION="0"
STYLE="0"


apt_get_everything()
{
#	sudo apt-get update
#	sudo apt-get upgrade
	sudo apt-get install -y arduino # Arduino IDE
	sudo apt-get install -y libftdi1 libelf1 # deps for avrdude.deb
	sudo apt-get install -y avr-libc binutils-avr gcc-avr avra # avr-gcc and friends
#	sudo apt-get install -y gdb-avr simulavr # debugging
#	sudo apt-get install -y cmake minicom bc evtest # misc tools
#	sudo apt-get install -y libusb-1.0-0-dev libusb-dev libftdi-dev libftdi1 libelf-dev autoconf bison flex # compile avrdude
}

compile_from_source()
{
	cd install/

	if [ ! -d avrdude-linuxgpio ]; then
		echo "avrdude-linuxgpio not found. Getting it..."
		git clone https://github.com/onandoffables/avrdude-linuxgpio || { echo "Error getting avrdude-linuxgpio"; exit 1; }
	fi

	cd avrdude-linuxgpio
	./install_avrdude.sh
	cd ..

	cd ..
}

install_bin()
{
	cd install/

	cd avrdude-bin
	./install_avrdude_bin.sh
	cd ..

	cd ..
}

patch_arduino()
{
	cd install/

	if [ ! -d arduino-linuxgpio ]; then
		echo "arduino-linuxgpio not found. Getting it..."
		git clone https://github.com/onandoffables/arduino-linuxgpio || { echo "Error getting arduino-linuxgpio"; exit 1; }
	fi

	cd arduino-linuxgpio
	./patch_arduino.sh
	cd ..

	cd ..
}

test_blinky()
{
	cd src/test/
	if [ "$BOARD" == "avrpi168" ]; then
		BRD=0 make flash
	elif [ "$BOARD" == "avrpi328" ]; then
		if [ "$SPEED" == "12000000" ]; then
			BRD=2 make flash
		elif [ "$SPEED" == "16000000" ]; then
			BRD=3 make flash
		else
			# 8000000
			BRD=1 make flash
		fi
	elif [ "$BOARD" == "avrpi32u4" ]; then
		BRD=4 make flash
	elif [ "$BOARD" == "gertboard328" ]; then
		BRD=5 make flash
	elif [ "$BOARD" == "gertduino328" ]; then
		BRD=6 make flash
		avrpi -r
	else
		echo "No blinky for you. Sorry."
		cd ../..
		return
	fi

	make clean
	cd ../..
}

install_wiringpi()
{
	cd install/

	if [ -d wiringPi ]; then
		echo "wiringPi found. updating..."
		cd wiringPi
		git pull origin
		./build
		cd ..
	else
		echo "First time git clone: installing"
		git clone git://git.drogon.net/wiringPi
		cd wiringPi
		./build
		cd ..
	fi
	
	cd ..
}

install_dfu_programmer()
{
	cd install/

	if [ -d dfu-programmer ]; then
		echo "dfu-programmer found. updating..."
		cd dfu-programmer
		git pull origin
	else
		echo "First time git clone: installing"
		git clone https://github.com/dfu-programmer/dfu-programmer
		cd dfu-programmer
	fi
	
	./bootstrap.sh
	./configure
	make
	sudo make install
	cd .. #dfu-programmer

	cd .. #install
}

install_avrpi()
{
	cd install/avrpi

	if [ -f /etc/avrpi.cfg ]; then
		echo "Old /etc/avrpi.cfg found. Backing up..." >&2
		sudo mv /etc/avrpi.cfg /etc/avrpi.cfg.bak
	else
		echo "/etc/avrpi.cfg not found. Installing avrpi default config..." >&2
	fi
	
	#local avrpi.cfg
	if [ -f avrpi.cfg ]; then
		#echo "Existing local config file found. Removing and creating new one..." >&2
		rm avrpi.cfg
	fi

	#avrpi_board
	echo "#avrpi_board can be avrpi168, avrpi328, avrpi32u4, gertboard328, gertduino328, gertduino48" >> avrpi.cfg
	echo "avrpi_board=$BOARD" >> avrpi.cfg
	echo "" >> avrpi.cfg
	
	#avrpi_chip
	echo "#avrpi_chip can be atmega168p, atmega328p, atmega32u4, atmega48p" >> avrpi.cfg
	echo "avrpi_chip=$CHIP" >> avrpi.cfg
	echo "" >> avrpi.cfg
	
	#avrpi_speed
	echo "#avrpi_speed 8000000, 12000000, 16000000" >> avrpi.cfg
	echo "avrpi_speed=$SPEED" >> avrpi.cfg
	echo "" >> avrpi.cfg
	
	#avrpi_programmer
	echo "#avrpi_programmer linuxgpio, gpio" >> avrpi.cfg
	echo "avrpi_programmer=linuxgpio" >> avrpi.cfg
	echo "" >> avrpi.cfg
	
	#avrpi_port
	echo "#avrpi_port /dev/ttyAMA0, /dev/ttyUSB0, /dev/ttyACM0" >> avrpi.cfg
	if [ "$CHIP" == "atmega32u4" ]; then
		echo "avrpi_port=/dev/ttyACM0" >> avrpi.cfg
	else
		echo "avrpi_port=/dev/ttyAMA0" >> avrpi.cfg
	fi
	echo "" >> avrpi.cfg
	
	#avrpi_baud
	echo "#avrpi_baud 9600, 38400, 57600, 115200 " >> avrpi.cfg
	echo "avrpi_baud=9600" >> avrpi.cfg
	echo "" >> avrpi.cfg
	
	#avrpi_delay
	echo "#avrpi_delay 0, 5 20 (isp clock delay)" >> avrpi.cfg
	echo "#anything other than 0 adds -i avrdude option" >> avrpi.cfg
	echo "avrpi_delay=5" >> avrpi.cfg
	#echo "" >> avrpi.cfg
	
	echo "Copy new avrpi.cfg to /etc/avrpi.cfg" >&2
	sudo cp avrpi.cfg /etc/avrpi.cfg
	echo "Copy avrpi to /usr/local/bin/avrpi" >&2
	sudo cp avrpi /usr/local/bin/avrpi
	
	avrpi -s
	
	echo "Cleaning up local avrpi.cfg..." >&2
	rm avrpi.cfg
	
	cd ../..
}

install_arduino_mk()
{
	cd src/
	./install_Arduino-Makefile.sh
	cd ..
	
	echo ""
	echo "Usage:"
	echo "  cd src/Arduino-Makefile/examples/Blink"
	echo "  [edit Makefile]"
	echo "  make avrpi"
}

install_LUFA()
{
	cd src/
	./install_LUFA-AVRPI32U4.sh
	cd ..
	
	echo ""
	echo "Usage:"
	echo "  cd src/LUFA-AVRPI32U4/examples/Keyboard"
	echo "  make avrdude"
	echo "  lsusb # look for USB device ('Atmel Corp. LUFA *')"
}

install_everything()
{
	apt_get_everything
	if [ "$STYLE" == "noob" ]; then
		install_bin
	elif [ "$STYLE" == "pro" ]; then
		compile_from_source
	fi
	patch_arduino
	install_wiringpi
	install_avrpi
}

set_fuse()
{
	#from factory: (E:xx, H:xx, L:xx)
	avrdude -i16 -c linuxgpio -p ${CHIP} -U efuse:w:$1:m -U hfuse:w:$2:m -U lfuse:w:$3:m
}

no_option()
{
	echo "'$1' is not a valid option."
	exit
}

fuse_menu()
{
	banner

	echo "  Fuse settings:"

	if [ "$BOARD" == "avrpi168" ]; then
		echo "    f)    set ATmega168p fuses (with crystal)"
	elif [ "$BOARD" == "avrpi328" ]; then
		echo "    f)    set ATmega328p fuses (with crystal)"
		echo "    g)    set ATmega328p fuses (with crystal + preserve EEPROM on erase)"
	elif [ "$BOARD" == "avrpi32u4" ]; then
		echo "    f)    set ATmega32U4 fuses (with crystal. recommended)"
		echo "    g)    set ATmega32U4 fuses (with crystal + HWB enabled)"
	elif [ "$BOARD" == "gertboard328" ]; then
		echo "    f)    set ATmega328p fuses (with crystal)"
	elif [ "$BOARD" == "gertduino328" ]; then
		echo "    f)    set ATmega328p fuses (with crystal)"
	elif [ "$BOARD" == "gertduino48" ]; then
		echo "    f)    set ATmega48p fuses (1 MHz)"
		echo "    g)    set ATmega48p fuses (8 MHz)"
	fi
	
	echo ""
	echo "Enter the fuse setting you want:"
	read fuse

	#set_fuse efuse hfuse lfuse
	if [ "$BOARD" == "avrpi168" ]; then
		#from factory: (E:01, H:DF, L:62)
		if [ "$fuse" == "f" ]; then
			set_fuse 0x00 0xDF 0xE7
		else
			no_option $fuse
		fi
	elif [ "$BOARD" == "avrpi328" ]; then
		#from factory: (E:07, H:D9, L:62)
		if [ "$fuse" == "f" ]; then
			set_fuse 0x07 0xD9 0xE7
		elif [ "$fuse" == "g" ]; then
			set_fuse 0x07 0xD1 0xE7
		else
			no_option $fuse
		fi
	elif [ "$BOARD" == "avrpi32u4" ]; then
		#from factory: (E:03, H:99, L:5E)
		if [ "$fuse" == "f" ]; then
			set_fuse 0xcb 0xd8 0xde
		elif [ "$fuse" == "g" ]; then
			set_fuse 0xc3 0xd8 0xde
		else
			no_option $fuse
		fi
	elif [ "$BOARD" == "gertboard168" ]; then
		#from factory: (E:F9, H:DF, L:62)
		if [ "$fuse" == "f" ]; then
			set_fuse 0x00 0xDF 0xE7
		else
			no_option $fuse
		fi
	elif [ "$BOARD" == "gertboard328" ]; then
		#from factory: (E:07, H:D9, L:62)
		if [ "$fuse" == "f" ]; then
			set_fuse 0x07 0xD9 0xE7
		else
			no_option $fuse
		fi
	elif [ "$BOARD" == "gertduino328" ]; then
		#from factory: (E:07, H:D9, L:62)
		if [ "$fuse" == "f" ]; then
			set_fuse 0x07 0xD9 0xE7
		else
			no_option $fuse
		fi
	elif [ "$BOARD" == "gertduino48" ]; then
		#from factory: (E:FF, H:DF, L:62)
		if [ "$fuse" == "f" ]; then
			set_fuse 0xFF 0xDF 0x62
		elif [ "$fuse" == "g" ]; then
			set_fuse 0xFF 0xDF 0xE2
		else
			no_option $fuse
		fi
	fi
}

banner()
{
	#clear
	echo ""
	echo "#######################################################################"
	echo "#                               AVRPi                                 #"
	echo "#######################################################################"
	echo ""
}

board_menu()
{
	banner

	#echo "    0)    AVRPi-168 (ATmega168p @ 8/12/16 MHz)"
	echo "  AVRPi-328"
	echo "    1)    ATmega328p @ 8MHz"
	echo "    2)    ATmega328p @ 12MHz"
	echo "    3)    ATmega328p @ 16MHz (overclocked)"
	echo ""
	echo "  AVRPi-32U4"
	echo "    4)    ATmega32U4 @ 8 MHz"
	echo ""
	echo "  Gertware"
	echo "    5)    Gertboard (ATmega328p @ 12 MHz)"
	echo "    6)    Gertduino (ATmega328p @ 16 MHz)"
	echo "    7)    Gertduino48 (ATmega48p @ 1 MHz)"
	echo "    8)    Gertduino48 (ATmega48p @ 8 MHz)"
	echo ""

	echo "What board do you have:"
	read BOARDNUM

	#if [ "$BOARDNUM" == "0" ]; then
	#	BOARD="avrpi168"
	#	CHIP="atmega168p"
	#	SPEED="8000000"
	#fi
	if [ "$BOARDNUM" == "1" ]; then
		BOARD="avrpi328"
		CHIP="atmega328p"
		SPEED="8000000"
	elif [ "$BOARDNUM" == "2" ]; then
		BOARD="avrpi328"
		CHIP="atmega328p"
		SPEED="12000000"
	elif [ "$BOARDNUM" == "3" ]; then
		BOARD="avrpi328"
		CHIP="atmega328p"
		SPEED="16000000"
	elif [ "$BOARDNUM" == "4" ]; then
		BOARD="avrpi32u4"
		CHIP="atmega32u4"
		SPEED="8000000"
	elif [ "$BOARDNUM" == "5" ]; then
		BOARD="gertboard328"
		CHIP="atmega328p"
		SPEED="12000000"
	elif [ "$BOARDNUM" == "6" ]; then
		BOARD="gertduino328"
		CHIP="atmega328p"
		SPEED="16000000"
	elif [ "$BOARDNUM" == "7" ]; then
		BOARD="gertduino48"
		CHIP="atmega48p"
		SPEED="8000000"
	else
		echo "Error. Please enter the number of the board."
		no_option $BOARDNUM
	fi
}

main_menu()
{
	echo "  Install everything in 1 easy step:"
	echo "    e)    use pre-compiled avrdude (like a noob)"
	echo "    z)    compile + install avrdude from source (like a pro)"
	echo ""
	echo "  Custom install:"
	echo "    a)    apt-get all prerequisites"
	echo "    p)    patch arduino"
	echo "    w)    install wiringPi"
	echo "    b)    install pre-compiled avrdude binary"
	echo "    c)    compile + install avrdude from source"
	echo "    v)    install avrpi tool"
	if [ "$BOARD" == "avrpi32u4" ]; then
		echo "    d)    install dfu-programmer"
	fi
	echo ""
	echo "  Fuses and test:"
	echo "    f)    set fuses for $CHIP"
	echo "    t)    make + upload test/blinky.hex"
	echo ""
	echo "  Extra software and projects:"
	echo "    m)    install Arduino-Makefile"
	if [ "$BOARD" == "avrpi32u4" ]; then
		echo "    l)    install LUFA-AVRPI32U4"
	fi
	echo ""
	echo "    q)    quit"
	echo ""
}

board_menu

while [ "$OPTION" != "q" ]; do

	banner
	echo "  chip:  $CHIP"
	echo "  speed: $SPEED"
	echo ""
	main_menu

	echo "Enter your choice:"
	read OPTION
	
	if [ "$OPTION" == "e" ]; then
		STYLE="noob"
		install_everything
	elif [ "$OPTION" == "z" ]; then
		STYLE="pro"
		install_everything

	elif [ "$OPTION" == "a" ]; then
		apt_get_everything
	elif [ "$OPTION" == "c" ]; then
		compile_from_source
	elif [ "$OPTION" == "b" ]; then
		install_bin
	elif [ "$OPTION" == "p" ]; then
		patch_arduino
	elif [ "$OPTION" == "w" ]; then
		install_wiringpi
	elif [ "$OPTION" == "d" ]; then
		install_dfu_programmer
	elif [ "$OPTION" == "v" ]; then
		install_avrpi

	elif [ "$OPTION" == "f" ]; then
		fuse_menu
	elif [ "$OPTION" == "t" ]; then
		test_blinky

	elif [ "$OPTION" == "m" ]; then
		install_arduino_mk
		exit
	elif [ "$OPTION" == "l" ]; then
		install_LUFA
		exit

	elif [ "$OPTION" == "q" ]; then
		exit
	else
		#no_option $OPTION
		echo "'$OPTION' is an unkown option."
	fi

done
